name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
steps:
  - name: Check the writing
    uses: bewuethr/mdl-action@v1
    with:
      style-file: .github/workflows/style.rb
      files: "README.md, conduct.md"
