name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - name: Check for existence of git files
    uses: andstor/file-existence-action@v1
    with:
      files: ".gitignore"    
